version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      foundation-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
